spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///bus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.qq.com
    port: 587
    username: 1650604245@qq.com
    password: uewqzbmzaxrqeadd
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    default-encoding: utf-8



#开启驼峰命名和下划线命名自动转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true



